language: java
sudo: required
jdk:
  - oraclejdk8

branches:
  only:
  - master

install:
  - pip install --user html5validator

before_script:
 -  chmod +x ./assets/dev/build

script:
  - ./assets/dev/build
  - html5validator --root _site/ --skip-non-css --ignore-re 'âš¡' 'custom-element' 'amp-boilerplate' 'amp-custom' 'on'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_install:
  - sudo update-ca-certificates
