# Site settings
title: TEDxAmstelveen
intro: TEDxAmstelveen - 2019 - 'Once Upon a Time...'
domain: TEDxAmstelveen
description: TEDx Amstelveen - 2019 - 'Once Upon a Time...'
cover: assets/cover/tedxamstelveen-once-upon-a-time-full.jpg

logo: assets/logos/TEDx_Amstelveen-logo.svg
logo-png: assets/logos/TEDx_Amstelveen-logo.png
logo1280-png: assets/logos/TEDx_Amstelveen-logo-1280.png

favicon: assets/icons/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://tedxamstelveen.com" # the base hostname & protocol for your site
robots: INDEX,FOLLOW
email: hallo@tedxamstelveen.com
fb_app_id: 144786006139437
paginate:	5 # The number of posts to show per page on your homepage

# Voorinschrijven
#form: https://goo.gl/kC3HNp
#formlogo: assets/blog/TEDx_Voorinschrijving.svg
# Wachtlijst
#form: https://goo.gl/u568Vk
#formlogo: assets/blog/TEDx_Wachtlijst.svg

# Social
facebook: tedxamstelveen
instagram: tedxamstelveen
twitter: tedxamstelveen
youtube: UC7pmtwbW_kN0ipHYpjgdAzA
flickr : tedxamstelveen

permalink: /:title/

# Google Analytics
analytics_id: UA-108379881-1

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
