# Site settings
title: TEDxAmstelveen
intro: TEDx Amstelveen - 2019 - 'Once Upon a Time...'
domain: TEDxAmstelveen
description: TEDx Amstelveen - 2019 - 'Once Upon a Time...'
cover: assets/cover/tedxamstelveen-2018.gif
logo: assets/logos/TEDx_Amstelveen-logo.svg
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://staging.tedxamstelveen.com" # the base hostname & protocol for your site
robots: NOINDEX,NOFOLLOW
email: hallo@tedxamstelveen.com
fb_app_id:
paginate:	25 # The number of posts to show per page on your homepage

# Social
facebook: tedxamstelveen
instagram: tedxamstelveen
twitter: tedxamstelveen
youtube: UCEmelQhyVjPdN07V286mt6g
flickr : tedxamstelveen

#Additional Pages
about: /about/
contact: /contact/
#privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id:

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
