---
new_page_extension: md
auto_deploy: false
admin_path: control
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: ''
  label: Pages
  create: all
upload_dir: assets/blog
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
